name: Deployment

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14
      - name: Cache dependencies and Astro build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-astro-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-astro-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build site
        run: bun run build
      - name: Upload artifact for VPS
        uses: actions/upload-artifact@v4
        with:
          name: vps-dist-files
          path: ./dist

  # deploy-gh:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4

  deploy-dm:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production  # 环境名称，比如 production, staging
      url: https://www.wingedge777.com/  # 这里填你的网址
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vps-dist-files # 对应上面的名字
          path: dist # 下载并解压到 dist 目录
      - name: Check files
        run: ls -R dist
      - name: Setup SSH Key
        env:
          deploy_key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          printf "%s\n" "$deploy_key" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via rsync
        env:
          port: ${{ secrets.VPS_SSH_PORT }}
        run: |
          
          echo "👉 Testing connection on port $port..."
          ssh -vvv -p $port -o BatchMode=yes -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "uptime"
          
          echo "👉 Starting rsync deployment..."
          rsync -avz \
          --chown=www-data:www-data \
          --delete \
          -e "ssh -p $port -o BatchMode=yes -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          dist/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/blog-site
